### ISSUE TITLE
End-to-end tests: expand AeaTestCase and and use it in tests

### ISSUE THREAD

**Issue by panasevychol** [fetchai/agents-aea#1005]
Currently most of end-to end tests extremely overweighted with repeatable code - file operations, CLI command calls, subprocesses, etc. We have AeaTestCase - a parent class with most usable operations (agents create, package settings update, install, etc.).

Currently we do not provide a test framework with helpful test classes for testing of AEAs

**Describe the solution you'd like**
Expand existing test case with more tools, use  it in other end-to-end tests. Develop such a framework and distribute it as part of the aea package

In particular:
- [x] create comprehensive test case class for end-to-end testing of (multiple) AEAs
- [x] add the test class as a core AEA module (`aea/test_tools`)
- [x] transition all existing end-to-end tests to use the new test case class (in `packages/tests_skills` and `packages/test_docs` as well as other end-to-end tests.)
- [x] add functionality to check for log output in test case
- [x] apply log output tests to all existing end-to-end tests (`tests/test_packages/skills` and `tests/test_docs/`)

**Comment by DavidMinarsch** [comment]
The way I imagine the test:
- in a yaml file provide a list of expected logger statements
``` yaml
expected_logs:
- some long log here
- some other log here
- some more here
- this is the last line
```
- while some timeout is not hit, watch stdout for the expected logs, if all logs are detected within timeout then stop and exit code 0, otherwise 1

The tools need to be exposed in the `AEATestCase`.
Each skill test (`tests/test_packages/test_skills/*`) needs to have such a test.

@marcofavorito did I miss anything?
