### ISSUE TITLE
Inconsistent Type Hints

### ISSUE THREAD

**Issue by 5A11** [fetchai/agents-aea#1593]
The existing type hinting in the project fails to correctly makes use of the `Type(X)` construct in mypy. 

Example: if the argument `x` of a method is supposed to be of type `A`, then it is type hinted as follows: `x: A`. However, if `x` is supposed to be of type `A` or any of its subclasses, it must be type hinted as follows: `x: Type(A)`. 

A number of places where this must be applied:
 * Most references to `Message`, `Dialogue` as typically a subclass, or concrete subclass of these is used in a skill's code (e.g. `handle(message: Message)`).
* References to `Message.Performative`

**Comment by marcofavorito** [comment]
@5A11 the notation `obj: SomeType` tells that `obj` is an instance of `SomeType`, hence also subclasses of that type. 

E.g. say we have an object `obj_1` of another type, `SubclassofSomeType`, which is a subtype of `SomeType`. Then, `obj_1` is an instance of `SomeType` too.

Another example:
```python
from abc import ABC


class A(ABC):
    pass

class B(A):
    pass

class C:
    pass


def foo(arg: A):
    print(arg)

b = B()
c = C()
foo(b)
foo(c)
```

Save it into a file, and run `mypy` against it. You will get:
```
mypy_issue.py:20: error: Argument 1 to "foo" has incompatible type "C"; expected "A"
Found 1 error in 1 file (checked 1 source file)
```

the call `foo(b)` is correct, because `b` is an instance of `B`, and therefore of `A`; the same cannot be said for `c`, hence the error.

Does that solve the issue? Also, I'm not aware of the notation `Type(x)` - maybe you meant `Type[X]`? If so, `Type[X]` is a "second-order" predicate; if you have `my_class: Type[X]`, then `my_class` is a type, that it is either `X` or one of its subclasses.

To show that, let's slightly modify the previous example:
```
from abc import ABC
from typing import Type


class A(ABC):
    pass

class B(A):
    pass

class C:
    pass


def foo(arg: Type[A]):
    print(arg)

b_class: Type[A] = B
c_class: Type[C] = C
foo(b_class)
foo(B)  # equivalent to the above line
foo(c_class)
foo(C)  # equivalent to the above line
```
You should get:
```
mypy_issue.py:22: error: Argument 1 to "foo" has incompatible type "Type[C]"; expected "Type[A]"
mypy_issue.py:23: error: Argument 1 to "foo" has incompatible type "Type[C]"; expected "Type[A]"
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by 5A11** [comment]
Thanks @marcofavorito. The above makes sense. I made a mistake in the description of the problem above. 
The problem I was observing is this:

```
class A: 
    def foo(arg: A):
        pass

class B(A):
    def foo(arg: B):
        pass
```

Having a super class `A` and method `foo` that operates on instances of `A`, I was after the functionality to _specialise_ `A`, by defining a subclass `B` with method `foo` which is specialised accordingly to operate on instances of `B`.

After some search, I realised this is not allowed by `mypy`. Once `foo` is defined to accept arguments of type `A`, this cannot be changed when overloading the method (even though the change is to specialise the arguments from `A`s to `B`s).

**Comment by marcofavorito** [comment]
Yes. Methods of subclasses can only accept arguments whose type is _wider or equal_ to the parent's one. More formally, it can be stated that "methods are contravariant with respect to parameter type".
E.g. https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Contravariant_method_parameter_type

**Comment by DavidMinarsch** [comment]
Happy we cleared this up :)
