### ISSUE TITLE
Extend documentation on contracts usage

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#2124]
**Is your feature request related to a problem? Please describe.**
@Totoual identified some gaps in the documentation on contracts, in particular with respect to cosmos.

**Describe the solution you'd like**
Add explanation regarding init vs deploy

**Comment by Totoual** [comment]
Since we are going to have the init function automatically called after the deploy on cosmos/fetchai smart contracts I don't think that we need to extend, but if we manually call the `get_init_transaction` then we will need to add an example of such a message. Also make sure that you point that the cosmos/fetchai smart contracts need more gas :)
