### ISSUE TITLE
Get_init_transaction is not called.

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#2143]
**Describe the bug**
`get_init_transaction` is not called if you don't overwrite it on the contract package. (For cosmos contract packages)

**To Reproduce**

Deploy a cosmos contract, and call the get_init_transaction.
ex message:

```
 contract_api_msg, contract_api_dialogue = contract_api_dialogues.create(
                counterparty=LEDGER_API_ADDRESS,
                contract_address="",
                performative=ContractApiMessage.Performative.GET_RAW_TRANSACTION,
                ledger_id=self.context.default_ledger_id,
                contract_id="aris/escrow:0.1.0",
                callable="get_init_transaction",
                kwargs=ContractApiMessage.Kwargs(
                    {"code_id": dict_tx["logs"][0]['events'][0]['attributes'][3]['value'],
                     "init_msg": {}}
                ),
            )
```

**Expected behavior**
Init function should have similar behaviour with the deploy transaction. Ideally, I would like to have a `GET_INIT_TRANSACTION` similar to `GET_DEPLOY_TRANSACTION`

**Comment by DavidMinarsch** [comment]
@Totoual I don't want to break the protocol at this point. I think we'll initially go for the approach where you need two deploy `GET_DEPLOY_TRANSACTION` messages, one for init and one for storage. Then via `kwargs` we know on framework side which one to use. I prefer this approach for now as it avoids a scenario where we introduce a specific functionality for one chain only. In many cases, you would only do the second call anyway, as the contract would already be on chain.

**Comment by DavidMinarsch** [comment]
On the framework, this means `get_deploy_transaction` (`https://github.com/fetchai/agents-aea/blob/develop/aea/crypto/cosmos.py#L464`) will, based on kwargs, call private `_get_init_transaction` or `_get_store_transaction` (current `get_deploy_transaction`). This also means the public methods are correct relative to ABC.

**Comment by jrriehl** [comment]
Makes sense to me @DavidMinarsch. I suppose another option would be to implement `GET_INIT_TRANSACTION` for EVM contracts as well, but if we don't have any of those implemented at the moment, that's probably a bit more work.

**Comment by DavidMinarsch** [comment]
@jrriehl to my knowledge there is no such distinction on EVM.

**Comment by Totoual** [comment]
So basically, we will need to call the deploy transaction twice. It is not the a difficult thing, but also not the cleanest approach. But as a temp thing it works.

**Comment by marcofavorito** [comment]
@Totoual thanks for the bug report. 

To summarize, we have these alternatives (integrate if you see others):
- use `GET_RAW_TRANSACTION` to call get_init_transaction ;
- use `GET_DEPLOY_TRANSACTION` to call private method `_get_init_transaction` (the dispatch will be done inside `get_deploy_transaction`)
- introduce a new performative `GET_INIT_TRANSACTION` and a new method `get_init_transaction` to the contract protocol/APIs and implement `get_init_transaction` when needed

My comments on the above:
- to use (1), we only need to implement `get_init_transaction` in Cosmos contract
- to use (2), we need both to implement `_get_init_transaction` and to modify `get_deploy_transaction` method
- to use (3), we need to change the contract protocol, update the contract interface, and implement `get_init_transaction` in Cosmos contract.

The easiest are (1) and (2). The only difference between the two is that with (2) we have a better conceptual separation of concerns; "init" and "deploy" actions are very similar as they are used only once at the beginning; instead, implementing `get_init_transaction` as a "raw message" would mix two concepts (what should be done at deployment time and at "contract runtime"). (3) is a bit more complex, but I see some value in it; however, my opinion is that I would wait for more use cases in order to introduce a new concept in the contract mechanism.
