### ISSUE TITLE
Skills Architecture

### ISSUE THREAD

**Issue by dishmop** [fetchai/agents-aea#318]
**Is your feature request related to a problem? Please describe.**
Skills framework seems unnecessarily heavyweight. 

**Background**
This is from following the Build your own skill tutorial. So I am probably missing a lot of additional context - but here are my thoughts anyway. 

I feel like the splitting of skills into Behaviours, Tasks and Handler classes adds unnecceasy complexity to the framework. It is a rather arbitrary splitting of responsibilities based on the characteristic of the code whereas if I had a large skill I would want to split it up based on more high-level areas of responsibilities (each one may involve a behaviour, handler and tasks) - and if I have, say 3, such areas of responsibility I’d probably want to have three classes - in this framework I may need nine. Needless to say for a much simpler skill, I’d just want to have one class (not three)

This splitting seems to also be the motivation for the “context” which is presumably needed because code in the behaviour, handle and task needs to get access to each other’s data. This seems like we are imposing a “system” where standard software engineering techniques specific to the task at hand are probably more appropriate. In the simple case, all the code for a skill should just be in one class and not need a "system" to communicate with itself. 

I propose that instead of having three classes, we have just a Skills class with optional overridable functions:
* setup
* act
* handle
* teardown

If you have “tasks” to do, you can just set them up as threads in the “setup” function. 

Another way to look at this is:
Are the tasks, behaviours and handlers something that can be swapped in and out for other ones? Like having written a skill can I decide - oh I’ll just swap out this handler for one in the aea package manager and it will just magically work better? I suspect this is not the case because for a given skill, the behaviour, tasks and handlers will be very tightly coupled. In which case we should not be imposing this kind of conceptual split - let developers decide how to split up their code unless we have a really good reason to restrict them,

**Comment by marcofavorito** [comment]
Thanks, @dishmop. I think this is a valuable discussion, and they are very valid points.

> I feel like the splitting of skills into Behaviours, Tasks and Handler classes adds unnecessary complexity to the framework. ...

Agreed. The split between `handlers`, `behaviours` and `tasks` is more a convention than a true separation of concerns. They are pretty interchangeable. It's more a way to think about an agent skill rather than have something different.
This observation is less true for `handlers` since they have the `def handle(message: Message, sender: str)` abstract method. This method is called in the framework during the dispatching of the envelopes. For `behaviours` and `tasks`, the difference is only in the namings: `act()` for the behaviours, `execute()` for tasks.

> I propose that instead of having three classes, we have just a Skills class with optional overridable functions...

Looks good. Very neat.

>Are the tasks, behaviours and handlers something that can be swapped in and out for other ones? Like having written a skill can I decide - oh I’ll just swap out this handler for one in the `aea` package manager and it will just magically work better? 

Yes, that is the case. And I believe this is a strength of the framework, although it's not enough to justify the separation in `handlers`, `behaviours`, `tasks` and `shared_classes`.
However, these are extra features that can be supported on the simple abstraction of `Skill` you mentioned above.

> ... let developers decide how to split up their code unless we have a really good reason to restrict them
Yes. Then, we can support skill templates, built on top of the simple `Skill` abstraction, to support the developers to standard solutions.

**Comment by marcofavorito** [comment]
Something like this:
```python

class SkillTemplate(Skill):

    def setup():
        # setup handlers...
        # setup behaviours...
        # setup tasks...

    def handle(envelope: Envelope):
        # should the skill be in charge of validating the envelope or the framework?

    def act():
        for b in behaviours:
            b.act()
    
    def teardown():
        # teardown handlers...
        # teardown behaviours...
        # teardown tasks...

```

Should the skill or the framework be in charge of validating the envelope? To discuss. Anyway, this was just to give idea.

**Comment by DavidMinarsch** [comment]
Thanks for the feedback.

I am not seeing the benefit of a single Skill Class which implements all the business logic (if you want to write such an agent then you can adopt an SDK approach to agent development). If you look at the existing examples, the amount of code even a simple skill like the weather skills require becomes very large very quickly. The current separation allows for a more modular approach which should lead to better understandable code (and even though skills internals are not shareable by default it should make it easier to reuse code from other skills via copy&paste).

The splitting of code between `Handler` and `Behaviour` and `Task` is not arbitrary but a convention which I think makes the framework actually less complex (it increases slightly the on setup/learning cost at the benefit of creating better patterns separating reactive and proactive behaviour, a key difference in agent vs client-server development). At the moment, the `Behaviour` and `Task` split is still purely by convention. This will change in the future, when `Task` will allow for long-running code, e.g. training a machine learning model and `Behaviour` will have better scheduling provided framework-side.

"This splitting seems to also be the motivation for the “context” which is presumably needed because code in the behaviour, handle and task needs to get access to each other’s data. This seems like we are imposing a “system” where standard software engineering techniques specific to the task at hand are probably more appropriate. In the simple case, all the code for a skill should just be in one class and not need a "system" to communicate with itself. "

Other than for superficially easy skills there is no way that you would be able to have a cleanly written skill in one class. Hence, whilst the "system" is certainly providing room for improvement, I would give us the benefit of the doubt here that this actually helps with writing skills. The "context" does not motivate the separation.

At this point, I believe strongly that we have good enough reasons to impose a system in the writing of skills. This will allow us over time to build guarantees into the framework around skill execution, sandboxing etc. (i.e. handlers and behaviours will be expected to not be blocking) and help us maintain a scalable framework.

Also, the web framework analogy is really important to keep in mind. Web frameworks are often highly opinionated but that allows them to establish patterns which allow for scaling and repeatable patterns so other developers can easily build on existing code.

@marcofavorito validation of envelope is always done by the framework. Validation of the message in the envelope will be done by the framework up to a point (depending on whether the protocols will be stateless or not). Ali is working on providing fundamental research here.

**Comment by dishmop** [comment]
in terms of the skill - yes an interface like this - though to be clear I would steer away from having a common base classes for behaviours, tasks and skills and I wouldn't try and push people towards that structure. Just if it makes sense for a particular skill to be broken down in this way - then that skill can do that. 

E.g. I would write the scaffold like this:

```
class SkillTemplate(Skill):

    def setup():
        # Initialise your skill

    def handle(envelope: Envelope):
        # Handle messages - you will only be passed messages which your skill supports

    def act():
        # Automatous actions - this function is called every Nth of a second
    
    def teardown():
        # clean up
```

**Comment by dishmop** [comment]
Now responding to David's post...

Well as I say I am coming at this from a position of ignorance, so am happy to give you the benefit of my doubts at the moment. I'll revisit this post when I have more experience with the framework and see how I feel about it then.

**Comment by marcofavorito** [comment]
> Just responding to Marco's post .... I haven't processed Davids yet.
> 
> in terms of the skill - yes an interface like this - though to be clear I would steer away from having a common base classes for behaviours, tasks and skills and I wouldn't try and push people towards that structure. Just if it makes sense for a particular skill to be broken down in this way - then that skill can do that.
> 
> E.g. I would write the scaffold like this:
> 
> ```
> class SkillTemplate(Skill):
> 
>     def setup():
>         # Initialise your skill
> 
>     def handle(envelope: Envelope):
>         # Handle messages - you will only be passed messages which your skill supports
> 
>     def act():
>         # Automatous actions - this function is called every Nth of a second
>     
>     def teardown():
>         # clean up
> ```

yes, what I meant is that, alongside a generic `Skill`, the user can decide to inherit either from our template, let's call it `HBTSkill` (`H` stands for handlers, `B` for behaviours and `T` for tasks), or from the standard skill.

so you can use the standard skill as:
```python

class MySkill(Skill):

    def setup():
        # Initialise your skill

    def handle(envelope: Envelope):
        # Handle messages - you will only be passed messages which your skill supports

    def act():
        # Automatous actions - this function is called every Nth of a second
    
    def teardown():
        # clean up

```

or our template skill (using the concepts of handlers, behaviours and tasks):

```python

class MySkill(BHTSkill):
    def setup():
        # setup handlers...
        # setup behaviours...
        # setup tasks...

    def handle(envelope: Envelope):
        # should the skill be in charge of validating the envelope or the framework?

    def act():
        for b in behaviours:
            b.act()
    
    def teardown():
        # teardown handlers...
        # teardown behaviours...
        # teardown tasks...

```

Hope I made my point clearer.

**Comment by DavidMinarsch** [comment]
----------

currently 2 levels of modularity:

- PyPi packages
- our packages: protocols, connections and skills


could have a third:

- common behaviours, handlers, shared classes exposed as modules

> use case driven

> search
> dialogue handling
> error handling
> ..

search:

class Behaviour

class Handler


---


from ... import Search

s = Search()

s.find(something)

**Comment by DavidMinarsch** [comment]
Another thought:

We could use decorators to let a developer define whether a function is part of a handler or behaviour. That way, a single file with a number of functions could implement a skill. (Behind the scenes this would utilise a number of virtual Behaviour, Handler etc. provided by the framework).
