### ISSUE TITLE
Duplicate Dialogue ID crash

### ISSUE THREAD

**Issue by dishmop** [fetchai/agents-aea#342]
**Describe the bug**
The weather station crashes if you start a dialogue with it and then start another dialog with the same dialogue ID. This is likely to also happen with other agents ad probably requires a system-wide solution.

**To Reproduce**
Run the weather station Ledger agent
Run the weather station client ledger agent (until it requests some data)
Shut down the client and re-run it

The weather station agent will crash.

**Expected behavior**
Weather station should return some kind of error "You have already used this ID". This should be part of the dialogue management.

**Comment by DavidMinarsch** [comment]
`dialogue_id` should be relabelled to `dialogue_nonce`..alternatively, use timestamping approach suggested by Katie

**Comment by DavidMinarsch** [comment]
The underlying issue here is that dialogue_id is a) an integer field; b) cannot be guaranteed to be unique for a pair of agents.

One solution is to split and rename this to `dialogue_starter_reference` and `dialogue_opponent_reference` and make it an opaque string field and then let the initiator of the dialogue define the `dialogue_starter_reference` with their preferred content. Then the actual `dialogue_id` is a unique identifier constructed as a Tuple of `dialogue_starter_pbk, dialogue_opponent_pbk, dialogue_starter_reference, dialogue_opponent_reference`. This way, the opponent can send the same `dialogue_reference` multiple times and it won't cause a clash.
