### ISSUE TITLE
Replace `class_name` with `class_path` in `skill.yaml`

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#993]
**Is your feature request related to a problem? Please describe.**
`class_name` is not enough to identify a component in the package.

For instance, for different models of skill, you can have the same model class with the same class name but in different Python modules. This is not desirable since currently one of the two is ignored, depending on the order the Python modules are analyzed.

**Describe the solution you'd like**

Instead of `class_name`, use `class_path` that is a dotted path to the class (to be intended from the root of the package), e.g.:
```
strategy.Strategy
behaviours.EchoBehaviour
handlers.EchoHandler
```
Of course, the name of the field `class_name` can be left as it is, but the type of accepted values changes.

**Describe alternatives you've considered**

**Additional context**
I think it should be extended to handlers and behaviours as well, although by "soft" convention they might not be in `handlers.py` and `behaviours.py`, respectively.

**Comment by DavidMinarsch** [comment]
So in this case, the question is whether it still makes sense to have the `handlers.py` and `behaviours.py` file name convention.

This change makes the configs even more verbose. Would it not be more desirable to enforce uniqueness of class-names within a skill. I.e. we throw an error message if multiple identical class names are present? I think this is more desirable as it biases towards 'lean' skills rather than 'fat' skills (which your suggested approach biases towards).
